# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: cloud.ga.gov.au
subtitle: Patterns and best-practices

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: ''

# Author/Organization info to be displayed in the templates
author:
  name: GA Autobots
  url: mailto:autobots@ga.gov.au

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/assets/img/ga-logo.png'
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: https://cloud.ga.gov.au/
- text: Getting Started
  subcategories:
  - text: Things to Consider
    url: things_to_consider_sub.html
    internal: true
  - text: Best Practices
    url: best_practices_sub.html
    internal: true
  - text: Setting Up AWS Account
    url: setting_up_aws_sub.html
    internal: true
  - text: Setting Up Continuous Delivery
    url: setting_up_cd_sub.html
    internal: true
  - text: Setting Up Cost Monitoring
    url: setting_up_cost_monitoring.html
    internal: true
  - text: Decommissioning Strategy
    url: decom_strategy_sub.html
    internal: true
- text: Patterns & Examples
  subcategories:
  - text: Guides
    url: guides_sub.html
    internal: true
  - text: AWS Examples
    url: aws_patterns_sub.html
    internal: true
- text: Tools
  url: tools_index.html
  internal: true
- text: Security 
  subcategories:
  - text: General Security
    url: general_security_sub.html
    internal: true
  - text: AWS Security
    url: aws_security_sub.html
    internal: true
  - text: Code Security
    url: code_security_sub.html
    internal: true
  - text: SSL & HTTPS
    url: ssl_sub.html
    internal: true
  - text: Authentication & SSO
    url: authentication_sub.html
    internal: true
  internal: true
- text: Code
  subcategories:
  - text: Code Review
    url: code_review_sub.html
    internal: true
  - text: Principles for Software Development
    url: coding_principles_sub.html
    internal: true
  - text: Testing
    url: testing_sub.html
    internal: true
- text: Release
  subcategories:
  - text: Release Checklists
    url: release_checklist_sub.html
    internal: true
  - text: Monitoring
    url: monitoring_sub.html
    internal: true
  - text: Failure Management
    url: failure_sub.html
    internal: true
  - text: Cost Management
    url: cost_management_sub.html
    internal: true
  - text: DNS Changes
    url: dns_changes_sub.html
    internal: true
  - text: Example Runbook
    url: runbook_sub.html
    internal: true


# Style Variables
brand_color: "#01708C"
